### ISSUE TITLE
Не работает переопределение

### ISSUE THREAD

**Issue by romankondratev** [f0rmat1k/bemy#28]
http://youtu.be/d4YqbQxLxkU

**Comment by f0rmat1k** [comment]
@romankondratev Привет.
1. Ты не мог бы мне прислать свой .bemy.json?
2. У тебя последняя версия bemy?
3. В storm'e можно включить вывод консоли в случае ошибок (в external tools). Скинь, пожалуйста, текст ошибки.

**Comment by romankondratev** [comment]
./.bemy.json

``` JSON
{
  "file-types": {
    "css": {
      "suffix": ".css",
      "shortcuts": [ "c", "css" ],
      "rename": ".{{bemNode}}",
      "template": "./node_modules/bemy/stub/style/style.css"
    },
    "styl": {
      "suffix": ".styl",
      "shortcuts": [ "s", "styl" ],
      "rename": ".{{bemNode}}",
      "template": "./node_modules/bemy/stub/style/style.styl"
    },
    "deps": {
      "suffix": ".deps.js",
      "shortcuts": [ "d", "deps" ],
      "template": "./node_modules/bemy/stub/depend/depend.deps.js"
    },
    "deps_dom": {
      "suffix": ".deps.js",
      "shortcuts": [ "dd", "ddom", "deps_dom" ],
      "template": "./node_modules/bemy/stub/depend/_dom/depend_dom.deps.js"
    },
    "bh": {
      "suffix": ".bh.js",
      "shortcuts": [ "b", "bh" ],
      "rename": "match('{{bemNode}}",
      "template": "./node_modules/bemy/stub/template/template.bh.js"
    },
    "priv": {
      "suffix": ".priv.js",
      "shortcuts": [ "p", "priv" ],
      "rename": [ "declare('{{bemNode}}", "block: '{{bemNode}}'", "block:'{{bemNode}}'" ],
      "template": "./node_modules/bemy/stub/template/template.priv.js"
    },
    "js_bl": {
      "suffix": ".js",
      "shortcuts": [ "jbl", "js_bl" ],
      "rename": "decl('{{bemNode}}",
      "template": [ "stub/script/_bl/script_bl.js" ]
    },
    "js": {
      "suffix": ".js",
      "shortcuts": [ "j", "js" ],
      "rename": [ "modules.define('{{bemNode}}", "@module {{bemNode}}", "@exports {{bemNode}}" ],
      "template": [ "stub/script/script.js" ]
    },
    "js_dom": {
      "suffix": ".js",
      "shortcuts": [ "jdom", "js_dom" ],
      "rename": [ "@module {{bemNode}}", "@class {{bemNode}}", "@lends {{bemNode}}", "@exports {{bemNode}}" ],
      "template": [ "stub/script/_dom/script_dom.js" ]
    }
  },
  "editor-open-command": "pstorm {{file-path}}:{{line-number}}",
  "bem": {
    "separators": {
      "elem": "__",
      "mod": "_",
      "modVal": "_"
    },
    "allowed-name-symbols-regexp": "[-a-z0-9]"
  },
  "deps_task": {
    "files": [ "css" ]
  },
  "debug": false,
  "checkForUpdate": true
}
```

Установка:

``` BASH
npm i -D bemy
```

Ошибка:

```
/usr/local/bin/bemy -t create -f /Users/romankondratev/Development/localhost/learning/project-stub/common.blocks/a -p j -g -o
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory '/Users/romankondratev/Development/localhost/learning/project-stub/stub/script/script.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at getTemplate (/usr/local/lib/node_modules/bemy/bemy.js:398:15)
    at createFileFromTemplate (/usr/local/lib/node_modules/bemy/bemy.js:251:27)
    at /usr/local/lib/node_modules/bemy/bemy.js:222:9
    at Array.forEach (native)
    at Object.startCreating (/usr/local/lib/node_modules/bemy/bemy.js:221:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/bemy/bemy.js:82:12)
    at Module._compile (module.js:460:26)

Process finished with exit code 1
```

**Comment by f0rmat1k** [comment]
Все верно, у тебя отсутсвуют пути к шаблонам, указанные в локальном конфиге.

**Comment by f0rmat1k** [comment]
Надо бы мне улучшить обработку этих ситуаций

**Comment by romankondratev** [comment]
Точно. =)
Менял по маске.
Искал:

```
"template": "stub/
```

Не обратил внимание на:

```
"template": [ "stub/
```

Спасибо за решение.
