### ISSUE TITLE
No such file or directory 'config.json'

### ISSUE THREAD

**Issue by belozer** [f0rmat1k/bemy#8]
установил `npm i bemy`
но при попытке создать блок  получаю ошибку
`node node_modules/bemy/bemy.js -t create -f common.blocks/scroller -p "css js"`

```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'config.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/sergey/sandbox/bem-bh/node_modules/bemy/bemy.js:14:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

OS ubuntu 14.10

**Comment by f0rmat1k** [comment]
Привет. Поправлено в 1.3.3. Проверь, пожалуйста.
